### PR TITLE
update to version 1.5.3

### PR DESCRIPTION
**Pull request by chegel**
update to version 1.5.3

**added "php${PHP_VERSION}-curl" to Dockerfile because of error:**
...
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for guzzle/guzzle v3.9.3 -> satisfiable by guzzle/guzzle[v3.9.3].
    - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
...

**added nodejs (npm, grunt-cli) in order to compile /assets from sources**

**added nano for editing ipconfig.php**

**make a copy of ipconfig.php and set writable permissions**

### CODE REVIEW

**Comment by chegel** [comment]
The only configuration step required is to edit and set InvoicePlane url.
Start containers:
`docker-compose up`
Login to docker invoiceplane container (docker ps for list of running container names):
`docker exec -it dockerinvoiceplane153_invoiceplane_1 bash`
edit ipconfig.php
`nano ipconfig.php`
IP_URL=http://localhost:10080
restart docker-compose:
`docker-compose up`

**Comment by ihr-it-projekt** [comment]
please merge this changes

**Comment by chegel** [comment]
I did not publish on docker hub, I am ok with sameersbn/docker-invoiceplane project. Why to create another branch?
It looks like I don't have permissions to merge this pull request to master (sameersbn/docker-invoiceplane project).

**Comment by j3k0** [comment]
It'd be better if we could all keep using @sameersbn / docker-invoiceplane. But after 3 months it seems like he wouldn't merge this update, so it might be worth creating an alternative (hopefully temporary) automated build for people to use...

**Comment by sameersbn** [comment]
hi. working on merging this

**Comment by sameersbn** [comment]
Hey @chegel are you able to use the download PDF option?

**Comment by chegel** [comment]
No

**Comment by sameersbn** [comment]
I've merged this PR into #15 and worked on fixing some of the issues. Please refer to the referenced PR for further discussion. This PR will be closed when #15 is merged

**Pull request merged**
